### PR TITLE
fixing greek and hebrew glyphs, symbols and punctuation in Thin and Thin Italic

### PR DESCRIPTION
**Pull request by KatjaSchimmel**
Hey Rasmus, I just started working on greek glyphs and will be working on language specific hebrew glyphs too. I will let you know, when there is a good amount of work done, for you to have a look :)

### CODE REVIEW

**Comment by KatjaSchimmel** [comment]
I finished fixing greek and hebrew glyphs in Thin and Thin Italic:
**greek:**
/Delta /Theta /Xi /Phi /Upsilonhooksymbol /beta /zeta /theta /xi /pi /rho /sigma1 /sigma /tau /upsilon /phigreek /phi /uni0370 /uni0372 /uni03D8 /Stigma /Digamma /Koppa /Sampi /uni03CF /uni03FD /mugreek /nu /uni0371 /uni0373 /uni0377 /uni037B /uni037C /uni037D /uni03D9 /stigma /digamma /koppa /sampi /uni03D7 /beta1 /thetasymbolgreek /pisymbolgreek /kappa1 /rho1 /uni03FB /uni03F6

Screenshot 2019-12-11 at 12 51 00


**hebrew:**
/finalkaf /finalmem /finaltsadi /qofdagesh

Screenshot 2019-12-11 at 13 42 14

Let me know if you find any issues.

**Comment by KatjaSchimmel** [comment]
Hey Rasmus, today I started working on symbols. Maybe we can wait with merging this PR, until after I'm done with them.  I will probably finish them tomorrow and post a list with all the glyphs fixed, here.

**Comment by KatjaSchimmel** [comment]
I finished checking the characterset and I think I caught and fixed all the extrapolation issues in Thin and Thin Italic. If you find more or there is any merge issue, please let me know. 

Here is the rest of the glyphs I worked on: 

Screenshot 2019-12-17 at 17 16 35


**symbols:** 
/response /Rx /yen /uni20BA /uni20BD /uni20B9 /uni20B9 /peseta /kip /won /hryvnia /uni20AF /mill /manat /lari /currency /openbullet /logicalnot /dagger /daggerdbl /section /partialdiff /summation /product /integral /radical /numero /eurocurrency /uni20B0 /uni20B6 /uni20B7 /uni20BB /uni2052 /lsquare /uni214F /versicle /lowdownarrowheadmod /plusmod /rhotichookmod /uni02EA /uni02EB /uni02F7 /uni02FA /uni02FC /uni02FE /uni02FF /tonebarextrahighmod.cn /tonebarextralowmod.cn /tonebarhighmod.cn /tonebarlowmod.cn /tonebarmidmod.cn /numeralgreeksub /uni02F1 /uni02F2

**punctuation:**
/caretinsertionpoint /charactertie /undertie /hyphendot /referencemark /uni204A /uni2053 /uni2054 /underscoredbl /quotereversed /uni27EF /uniA92E 

**fixing remaining extrapolation errors:**
/Eng /mturndescend /uni1DBF /Omegaroundcyrillic /omegaroundcyrillic /Omegatitlocyrillic /omegatitlocyrillic /Otcyrillic /otcyrillic /uni2DFF /uni1FFD /uni20E3

**Comment by rsms** [comment]
A M A Z I N G 
W O R K
!

**Pull request merged**
