### PR TITLE
Add U+2236 'RATIO'

### LINKED ISSUE #278: 'RATIO' (U+2236) in bold variant looks too thin and spaces are too wide
**Describe the bug**
I think the 'RATIO' (U+2236) is missing. 

**To Reproduce**
1.  See this string: Mi Mai 6 09‎∶06

**Expected behavior**
`∶` should look like `:` with regard to thickness and spacing.

**Screenshots**
This is my GNOME clock:
Screenshot from 2020-05-06 08-59-49

Font viewer:
Screenshot from 2020-05-06 10-19-56

**Environment**
- Ubuntu 20.04 in a GNOME session
- GNOME Panel
- Inter Regular and Bold 3.013;git-d82f67bfa

**Additional context**
*I think there not much more to say, it there?*

### PR DESCRIPTION
**Pull request by hcsch**
GNOME uses this symbol as the seperator between hours, minutes and
seconds. If Inter does not provide this symbol the renderer will fall
back to another font, possibly causing inconsistently spaced/weighted
timestamps.

Fixes #278

This is my first time working with `.glyphs` files and I also did that in a text-editor, not the Glyhps app. I mimicked the glyph code for U+EE01, but also added `widthMetricsKey = colon.case`, since that seems to be an option to keep glyph widths synchronized. 
Another thing I'm unsure about is the docs directory and the data about the glyphs in there, should that be regenerated and if yes, how? I didn't really find anything about that.
While looking at U+EE01 I also noticed that it isn't present in InterDisplay, is that intentional? If no, I can open another issue and fix that later. If yes, a comment explaining why might be sensible, so that future contributors don't need to guess.

If anything seems off to you, feel free to tell me and I'll adjust the PR accordingly :)
Thanks for making this font btw. I really quite like it ^^

### CODE REVIEW

**Comment by hcsch** [comment]
For an example of what this change looks like in the wild (minus the pink underlines for emphasis):
image

**Comment by rsms** [comment]
Thank you! Let me find some time to have a look at this before the merge.

**Comment by rsms** [comment]
Looks good to me. Would you mind rebasing on the latest upstream as this patch has drifted far enough that there are conflicts

**Comment by hcsch** [comment]
Hmm... I'm having trouble building skia-pathops as it somehow still requires python2 in some capacity (don't have that installed anymore):
<details>
<summary>Click to show the error</summary>

```
--- snip ---
Building wheels for collected packages: skia-pathops
  Building wheel for skia-pathops (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/hcsch/projects/font/inter/build/venv/bin/python /home/hcsch/projects/font/inter/build/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpalgmpyl1
       cwd: /tmp/pip-install-0ofhr0cy/skia-pathops_86a2d4a398e3425886b0a11ceb636d53
  Complete output (16 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.10
  creating build/lib.linux-x86_64-3.10/pathops
  copying src/python/pathops/operations.py -> build/lib.linux-x86_64-3.10/pathops
  copying src/python/pathops/__init__.py -> build/lib.linux-x86_64-3.10/pathops
  copying src/python/pathops/_version.py -> build/lib.linux-x86_64-3.10/pathops
  running build_ext
  creating build/temp.linux-x86_64-3.10
  creating build/temp.linux-x86_64-3.10/src
  creating build/temp.linux-x86_64-3.10/src/python
  creating build/temp.linux-x86_64-3.10/src/python/pathops
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fPIC -Isrc/cpp/skia-builder/skia -Isrc/cpp/skia-builder/skia/src -I/home/hcsch/projects/font/inter/build/venv/include -I/usr/include/python3.10 -c src/python/pathops/_pathops.cpp -o build/temp.linux-x86_64-3.10/src/python/pathops/_pathops.o -std=c++14
  error: [Errno 2] No such file or directory: 'python2'
  ----------------------------------------
  ERROR: Failed building wheel for skia-pathops
Failed to build skia-pathops
ERROR: Could not build wheels for skia-pathops, which is required to install pyproject.toml-based projects
```
</details>

Even if I install python2 again, building that wheel fails in the virtualenv:
<details>
<summary>Click to show the error</summary>

```
Building wheels for collected packages: skia-pathops
  Building wheel for skia-pathops (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/hcsch/projects/font/inter/build/venv/bin/python /home/hcsch/projects/font/inter/build/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp425k4mb2
       cwd: /tmp/pip-install-u6umayi7/skia-pathops_6f9ebda72811423b90c9079c9de539e2
  Complete output (78 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.10
  creating build/lib.linux-x86_64-3.10/pathops
  copying src/python/pathops/operations.py -> build/lib.linux-x86_64-3.10/pathops
  copying src/python/pathops/__init__.py -> build/lib.linux-x86_64-3.10/pathops
  copying src/python/pathops/_version.py -> build/lib.linux-x86_64-3.10/pathops
  running build_ext
  creating build/temp.linux-x86_64-3.10
  creating build/temp.linux-x86_64-3.10/src
  creating build/temp.linux-x86_64-3.10/src/python
  creating build/temp.linux-x86_64-3.10/src/python/pathops
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fPIC -Isrc/cpp/skia-builder/skia -Isrc/cpp/skia-builder/skia/src -I/home/hcsch/projects/font/inter/build/venv/include -I/usr/include/python3.10 -c src/python/pathops/_pathops.cpp -o build/temp.linux-x86_64-3.10/src/python/pathops/_pathops.o -std=c++14
  AttributeError: DistutilsMetaFinder instance has no attribute 'find_module'
  Traceback (most recent call last):
    File "/home/hcsch/projects/font/inter/build/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/hcsch/projects/font/inter/build/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/hcsch/projects/font/inter/build/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-r8gxcszm/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 230, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-r8gxcszm/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-r8gxcszm/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 267, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-r8gxcszm/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 367, in <module>
      setup(**setup_params)
    File "/tmp/pip-build-env-r8gxcszm/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 155, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-r8gxcszm/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
      return run_commands(dist)
    File "/tmp/pip-build-env-r8gxcszm/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-r8gxcszm/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-r8gxcszm/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-r8gxcszm/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/tmp/pip-build-env-r8gxcszm/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-r8gxcszm/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-r8gxcszm/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/tmp/pip-build-env-r8gxcszm/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-r8gxcszm/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "setup.py", line 216, in run
      build_ext.run(self)
    File "/tmp/pip-build-env-r8gxcszm/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/tmp/pip-build-env-r8gxcszm/overlay/lib/python3.10/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "/tmp/pip-build-env-r8gxcszm/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/tmp/pip-build-env-r8gxcszm/overlay/lib/python3.10/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
      _build_ext.build_ext.build_extensions(self)
    File "/tmp/pip-build-env-r8gxcszm/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/tmp/pip-build-env-r8gxcszm/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "setup.py", line 194, in build_extension
      libraries=self.get_libraries(ext),
    File "setup.py", line 210, in get_libraries
      library_dir = self._library_builders[library](self.build_temp)
    File "setup.py", line 269, in build_skia
      subprocess.run(build_cmd, check=True, env=env)
    File "/usr/lib/python3.10/subprocess.py", line 524, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['python2', 'src/cpp/skia-builder/build_skia.py', 'build/temp.linux-x86_64-3.10/src/cpp/skia-builder/skia']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for skia-pathops
Failed to build skia-pathops
ERROR: Could not build wheels for skia-pathops, which is required to install pyproject.toml-based projects
```
</details>

Bulding the skia-pathops wheel works with version 0.7.2, but after that I get build failures when trying to build the font files with `make -j test`:
<details>
<summary>Click to show the error</summary>

```
misc/fontbuild glyphsync -o build/ufo src/Inter.glyphs
Traceback (most recent call last):
  File "/home/hcsch/projects/font/inter/misc/fontbuild", line 22, in <module>
    from fontbuildlib import FontBuilder
  File "/home/hcsch/projects/font/inter/misc/fontbuildlib/__init__.py", line 1, in <module>
    from .builder import FontBuilder
  File "/home/hcsch/projects/font/inter/misc/fontbuildlib/builder.py", line 2, in <module>
    import ufo2ft
  File "/home/hcsch/projects/font/inter/build/venv/lib/python3.10/site-packages/ufo2ft/__init__.py", line 14, in <module>
    from ufo2ft.preProcessor import (
  File "/home/hcsch/projects/font/inter/build/venv/lib/python3.10/site-packages/ufo2ft/preProcessor.py", line 6, in <module>
    from ufo2ft.filters import loadFilters
  File "/home/hcsch/projects/font/inter/build/venv/lib/python3.10/site-packages/ufo2ft/filters/__init__.py", line 9, in <module>
    from .cubicToQuadratic import CubicToQuadraticFilter
  File "/home/hcsch/projects/font/inter/build/venv/lib/python3.10/site-packages/ufo2ft/filters/cubicToQuadratic.py", line 3, in <module>
    from cu2qu.pens import Cu2QuPointPen
  File "/home/hcsch/projects/font/inter/build/venv/lib/python3.10/site-packages/cu2qu/__init__.py", line 23, in <module>
    from .cu2qu import *
ImportError: /home/hcsch/projects/font/inter/build/venv/lib/python3.10/site-packages/cu2qu/cu2qu.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send
make: *** [Makefile:165: build/ufo/Inter.designspace] Error 1
```
</details>

This last issues seems to be a problem with cython. I guess I could try installing a different version of python, but if you're alright with that, I'd just try rebasing my changes sort-of blind, if you could build them. They are after all just a few lines that really should not break anything, especially since it's mostly the same as `uniEE01`.

**Comment by hcsch** [comment]
I've pushed a rebased version now, but I had to disable the git hook, because they were preventing me from doing anything due to the build issues with skia-pathops, so you probably want to check if everything still builds and passes tests for you.
I can try getting it to work again on my machine as well, but I'm a bit busy this week, so it might take me a bit.

**Comment by hcsch** [comment]
I've rebased against master now. The ratio glyph definition for Inter I've now basically 1:1 duplicated from uniEE01, the one for InterDisplay has stayed the same, since that doesn't seem to have changed.
I'm still having some troubles getting stuff to build (though at least the git hooks work for me now). Some gftools protobuf stuff is failing (probably because of a newer system protobuf version than what was used to generate the the code), but that can be circumvented by downgrading protobuf / using the pure-Python implementation (both workarounds that are suggested along with the error). Additionally however, after applying the latter workaround, building fails in one of the inter scripts with the following traceback:
```
Traceback (most recent call last):
  File "/home/hcsch/projects/inter/misc/tools/postprocess-single-axis-vfs.py", line 301, in <module>
    main()
  File "/home/hcsch/projects/inter/misc/tools/postprocess-single-axis-vfs.py", line 295, in main
    harmonize_vf_families(ttfonts)
  File "/home/hcsch/projects/inter/misc/tools/postprocess-single-axis-vfs.py", line 274, in harmonize_vf_families
    family_styles = _get_vf_types(ttfonts)
  File "/home/hcsch/projects/inter/misc/tools/postprocess-single-axis-vfs.py", line 156, in _get_vf_types
    styles.append(_get_vf_type(ttfont))
  File "/home/hcsch/projects/inter/misc/tools/postprocess-single-axis-vfs.py", line 161, in _get_vf_type
    style = ttfont['name'].getName(2, 3, 1, 1033).toUnicode()
AttributeError: 'NoneType' object has no attribute 'toUnicode'
```

**Comment by rsms** [comment]
InterDisplay.glyphs is deprecated (work is being done to add an opsz axis to Inter instead) so you "only" need to update the 12 glyphs of Inter.

**Comment by hcsch** [comment]
I've removed that changes to InterDisplay and rebased onto master again.

**Pull request merged**
