### PR TITLE
fixing diacritics and latin glyphs in thin and thin italic master

### PR DESCRIPTION
**Pull request by KatjaSchimmel**
Hey Rasmus! Just starting this Pull Request. Will add more to it later

### CODE REVIEW

**Comment by KatjaSchimmel** [comment]
Until now, I worked on following glyphs in thin and thin italic:

- diacritic marks (used as components):
/hungarumlaut /tonostop /dieresistonos /gravecomb /brevenosp /brevesubnosp /commaturnedmod /cedillanosp /glottalstopmod /glottalstopreversedmod /linevert /verticallinelowmod /candrabindunosp /commaturnsupnosp /uptackmod /tackleftsubnosp /anglesupnosp /hooksubpalatnosp /archdblsubnosp /breveinvnosp /breveinvsubnosp /underscoredblnosp /barmidlongnosp /slashshortnosp /uni02FD /squaresubnosp /xsupnosp /tildevertsupnosp /tildedoublecmbn /overscoredblnosp /uni0349 /uni034A /uni034B /uni034C /uni034D /uni034E /uni0351 /uni0352 /uni0353 /uni02F0 /uni02F2 /uni02F1 /uni0359 /uni035A /uni1DFC /uni035D /uni1DFC /uni035D /uni035E /uni0362 /uni1DC2 /uni1DC3 /uni1DC5 /uni1DC4 /uni1DC6 /uni1DC7 /uni1DC9 /uni1DC8 /uni1DC9 /uni1DCB /uni1DCC /uni1DCD /uni1DD0 /uni1DD1
/uni20F0 /uniFE20 /uniFE29 /uniFE2A /uniFE26 /uniFE25 /uniFE24 /macrongravecomb.lc /iotasubnosp /hornnosp /uni1FBD /uni1FBF /uni1FFE /uni1FCD /uni1FDD /uni1FCE /uni1FDE /uni1FCF /uni1FDF /uni1FED /uni1FEE /uni1FC1 /uni1FEF /titlocyrilliccmb /palatalizationcyrilliccmb /dasiapneumatacyrilliccmb /palatalizationcyrilliccmb /psilipneumatacyrilliccmb /uni0487 /uni1DD2 /uni1DE8 /uni1DEA /uni1DEB /uni1DEC /uni1DED /uni0369 /uni1DEF /uni1DF0 /uni1DF2 /uni1DF2 /uni1DF3 /uni1DF4 /uniA69F /uni0363 /uni0368 /uni036A /uni036B /uni036C /uni036D /uni036F /uni1DCA /uni1DD3 /uni1DD4 /uni1DD5 /uni1DD9 /uni1DD8 /uni1DE7 /uni1DDA /uni1DDB /uni1DDC /uni1DDD /uni1DDE /uni1DDF /uni1DE1 /uni1DE2 /uni1DE3 /uni1DE4 /uni1DE5 /uni1DE6 /uni1DE9 /uni0488 /uni0489 /caroncmb /caronbelowcmb /uni02F3

- "private use" glyphs:
/acutedotcomb.lc /tildedieresiscomb /carondotcomb.lc /caronnosp /dieresiscaroncomb.lc /dieresiscaroncomb.cn /carondotcomb.cn /dieresisgravecomb.lc /tildedieresiscomb.cn /macrondieresiscomb.cn /macrondieresiscomb.lc /dieresisgravecomb.cn /cyrillichookleft /tildemacroncomb.cn /tildemacroncomb.lc /circumflexgravecomb.cn /circumflexacutecomb.cn /circumflexhookcomb.cn /circumflextildecomb.cn /largerighthook /breveacutecomb.cn /brevegravecomb.cn /acutedotcomb.cn /brevetildecomb.cn /commaaccentrotate.cn /brevehookcomb.cn
glyphs with non-component diacritic marks:
/uni023A /uni023B /uni0246 /uni023E /Bhook /Dhook /Ghook /Ghook.1 /Thook /Hbar /Phook /afii10147 /Lslash /Ohorn /Uhorn /Nhook /Fhook /Trthook /uni024C /uni01F6 /Khook /uni0244 /Yhook /uni024E /uni0224 /uni2C7F /bhook /chook /drthook /dhook /ghook /hhook /henghook /hturnlthook /hturnhook2 /khook /lrthook /mhook /nrthook /nlfthook /phook /qhook /qrthook /Q_rthook /rfishhookrev /rfishhook /rrthook.1 /srthook /tpalatalhook /trthook /yhook /zhook /uni023C /uni0247 /eng /lslash /lslash.ss02 /ohorn /uhorn /fitacyrillic /uni023F /tbar /ubar /uni024F /uni0240 /lbelt.ss02 /epsilon1revhook

- latin glyphs:
/germandbls /germandbls.1 /Germandbls /ccurl /uni0221 /jcrosstail.ccmp /lbelt /lcurl /ncurl /zcurl /dyogh /Thorn /Omega /Upsilon2 /Gamma1 /eth /thorn /epsilon /epsilonclosed /gamma1 /florin /ordfeminine /ordmasculine /Btopbar /Dtopbar /Epsilon1 /Sigma /Iota1 /OI /Schwa /Tonesix /Vcursive /YR /mcapturn /uni01F7 /uni0220 /uni0241 /uni0245 /uni1EFC /uni1EFE /Gsmallcaphook /Gsmallcap /Ismallcap /Lsmallcap /Nsmallcap /OEsmallcap /Rsmallcap /Ysmallcap /alpha /ascriptturn /babygamma /cstretch /deltaturn /erev /esh /eshcurleshcurl /eshlooprev /schwahook /ezhcurl /ezhtail /glottalstopbar /glottalstopbarinv /glottalstoprevinv /uni021D /iota1 /kgreenlandic /lambda /lambdabar /lyogh /oi /omega /omegaclosed /oopen /philatin /rturnascend /longs /tesh /thook /tonefive /tonesix /ts /uni0223 /uni0238 /uni0239 /uni0242 /vecyrillic /uni02AB /uni02AC /uni1E9D /delta /uni1EFD /uni1EFF /uni2184 /upsilonlatin /vscript /Rturnsuper /hhooksuper /uni2094 /uniA7FF /uni2071.ccmp /glottalstopreversed.numr /uni02B2.ccmp /uni2180 /uni2182 /uni2183 /uni2185 /uni2186 //uni2188 /gammasuper /hv

**Comment by KatjaSchimmel** [comment]
Hey hey, I just removed the overlap in /uni0224 and /Yhook. Let me know if there are still issues with it.

I was having a look at other letters with a "hook" and found some more that could benefit from removing the overlap (between stem and hook):
/yhook /qrthook /khook /Thook
Screenshot 2019-11-26 at 08 58 01

Unlike the other hook letters (which are components with a hook attached, e.g. /Trhook), they resemble /uni0224 and /Yhook in the way they are drawn (disassembled and modified base letters with a hook, e.g. /Thook).
Screenshot 2019-11-26 at 09 09 52

As those letters didn't cause any issues, we could keep them like they are. But maybe it's nice to remove the overlap, for consistency in the drawing?

**Comment by rsms** [comment]
> As those letters didn't cause any issues, we could keep them like they are. But maybe it's nice to remove the overlap, for consistency in the drawing?

For glyphs not using components I think we should.
For glyphs that do use components, I think the upside of components outweighs the hassle with overlap removal :–)

**Comment by rsms** [comment]
This looks *really great*!
I’m going to merge this PR and we can start a new one for the next set of changed.
Fantastic work Katja!

**Comment by rsms** [comment]
Sample: https://rsms.me/etc/inter-thin-wip-20191127.html
[sample.svg.zip](https://github.com/rsms/inter/files/3899277/sample.svg.zip)

**Pull request merged**
