### PR TITLE
adjust bottom accents for improved line heights

### PR DESCRIPTION
**Pull request by thundernixon**
This PR makes several small but useful changes to close issue https://github.com/rsms/inter/issues/145, and bring Inter more into the default line height range of comparable UI fonts:

- Adjusts `bottom` anchor on /y to move dot to the side of /ydotbelow, as in comparable fonts
    - (The /y glyph has no other accents below, so it doesn’ spill over)
- Makes /commabelow accent slightly more compact, so it doesn’t go too far past descender
- Gives /t a `bottom` anchor to make sure /commabelow accent is visually centered

image

(It also increments the version number to `3.005`)

### CODE REVIEW

**Comment by thundernixon** [comment]
@rsms I was somewhat conservative on how much I adjusted the /commaaccent, here. As you can see, it's still a bit bigger in Inter than other families. If you want to, it might be worth making it a bit more compact, still. Then again, it's probably not such a bad thing for default line height to be a bit generous, as it will typically make text more readable. 

In #145, you mentioned you could take a look at this tonight. Great! Feel free to use this PR as a starting point it you like, or you can start the changes from scratch. 

One thing I'm noticing is that, with this PR, the overall default line height is better, _but_ it's less-nice if you take common UI needs into account, such as vertically centering text in a button. For example, here's SF & Inter 3.005, without explicit line height, just auto-centered in a button shape, in Sketch:

image

image

I tend to think that button text looks best if Latin caps are vertically centered, so SF looks better to me in this case.

You can probably fairly safely adjust the winAscent & winDescent values in a way that is slightly separated from actual min/max Y coordinates, but just with the caveat that certain apps may cut off those areas. Still, easy vertical centering is probably of more importance to this family than making sure the /Aring is 100% visible in something like a VS Code terminal (the only context in which I can remember pieces of letters being partially covered).

So, you can do tests on your own, but I would recommend:
1. Making the /commaaccent slightly more compact
2. Bringing down the winAscent by a bit (maybe to the top of the /Atilde or something), and seeing whether that vertically centers things in a way that you find suitable

**Comment by rsms** [comment]
Thank you so much for this!

It seems the changes were made on top of a fairly dated master — I ran MergeGlyphs on master vs this, and there are a lot of changes, including missing glyphs.

I'm going to manually introduce these changes onto latest master, and probably include a few small touch-ups to the /y shape while I'm at it.

**Comment by thundernixon** [comment]
> It seems the changes were made on top of a fairly dated master — I ran MergeGlyphs on master vs this, and there are a lot of changes, including missing glyphs.

😬Oof, I guess I missed merging in your latest changes – glad you caught that. 

The changes were pretty quick, so it shouldn't take you long. Thanks for taking a look!

**Comment by thundernixon** [comment]
(Feel free to close this unless you intend to make the edits within this PR)

**Comment by rsms** [comment]
Landed. Thanks again :–)

**Pull request closed without merging**
