### PR TITLE
Add Android's custom U+EE01 vertically-centered colon codepoint

### PR DESCRIPTION
**Pull request by kdrag0n**
Android's default system font, Roboto, does not have a calt alternative to vertically center the colon when it's next to a number. Instead, it uses a Private Use Area codepoint, U+EE01, for its vertically-centered colon symbol that is used on the lock screen clock.

This adds U+EE01 as a duplicate of U+E092 `/colon.case`, since that character is a vertically-centered colon -- exactly what we're looking for in this case. The font is fully usable as an Android system font after this change.

### CODE REVIEW

**Comment by rsms** [comment]
That’s a really weird quirk of Android! :–)
I’ll look into merging this as soon as I can find some time.
Thank you

**Comment by rsms** [comment]
Thanks for the updates. However it seems like the Black and Black Italic master glyphs are missing components:
Screen Shot 2020-01-31 at 22 28 17

**Comment by kdrag0n** [comment]
Fixed, sorry for the trouble — this is my first time editing a font.

**Comment by lazerl0rd** [comment]
I can confirm that Android does have this issue and hopefully the latest force-push by kdrag0n has sufficed the requested changes, as this is a great font to use for mobile UI but has the caveat of a broken lock screen clock on many devices currently.

**Comment by kdrag0n** [comment]
Rebased onto latest master to fix conflicts.

**Comment by rsms** [comment]
Thank you!

**Comment by rsms** [comment]
This has now been released as part of [version 3.14](https://github.com/rsms/inter/releases/tag/v3.14) 🎉

**Pull request merged**
