### PR TITLE
Adding new currencies

### PR DESCRIPTION
**Pull request by NaN-xyz**
The currencies are:
— Georgian Lari (ლ) [glyph name: las-georgian];
— New Taiwan Dollar (元) [glyph name: uni5143];
— Afghan Afghani (؋) [glyph name: afghani-ar];
— Arabic Rial (﷼) [glyph name: uFDFC];
— Bengali Rupee (৳) [glyph name: rupeeSign-beng];
— Khmer Riel (៛) [glyph name: u17DB];
— Moroccan dirham (written د.م. with Arabic letters + a precomposed glyph in private unicode E1B0) [glyph name: MoroccanDirham-ar];
— UAE dirham (written د.إ. with Arabic letters + a precomposed glyph in private unicode E1B1) [glyph name: UAEdirham-ar].

### CODE REVIEW

**Comment by rsms** [comment]
These are truly beautifully made!
Thank you so much for contributing to Inter ♡

Screen Shot 2022-07-09 at 14 01 50

**Comment by rsms** [comment]
I wonder if we could generate `/MoroccanDirham-ar` using components `meem-ar + period + dal-ar`? (Same for `/UAEdirham-ar`)

Screen Shot 2022-07-09 at 14 08 49

**Comment by rsms** [comment]
Tried generating /MoroccanDirham-ar with components and it seems that the dot is slightly larger than period, but otherwise the shapes match (with a very small difference in shapes, perhaps from an earlier version?)

rast8e21

Does the center column with the componentized glyph look good to you @NaN-xyz?

**Comment by rsms** [comment]
@NaN-xyz I notice that /MoroccanDirham-ar and /UAEdirham-ar have no corresponing Unicodes — are they ligatures? If so, we should add OT feature rules for them in either ccmp or liga.

**Comment by YVVT** [comment]
Remove 元, please. It's NOT a currency symbol, not at all. The symbol for NTD is $. (Mainland China is also using 元, but the symbol is ￥.) 元 is just a CJK unified ideograph, just like any other CJK unified ideograph. When used with another CJK font, the text would look strange.

**Pull request merged**
