### PR TITLE
Add capital letter `I` serif to salt.fea

### PR DESCRIPTION
**Pull request by hydino2085143**
This is a self explanatory change, correcting a small oversight in salt.fea

### CODE REVIEW

**Comment by rsms** [comment]
> "self explanatory change"

I'm afraid not. Can you please talk a bit about why you think Stylistic Alternates should turn on the "capital i with serif"?

**Comment by hydino2085143** [comment]
Capital I with serif is a different style of the letter Uppercase I. Lowercase l, which has a Disambiguation form with a curved tail, is also included under the `salt` feature. https://github.com/rsms/inter/blob/13b53990e73ddb73f9545215abf1733fa56f9b6f/src/features/salt.fea#L53-L65

**Comment by rsms** [comment]
Maybe the salt feature should be removed? It's been years since I added it and I can't remember why (and I can't figure out when it would be useful today.)

**Comment by rsms** [comment]
Anyhow, thank you for this

**Comment by hydino2085143** [comment]
I use it to quickly test stylistic alternates when designing, though I'm not sure what practical usage it has.

**Pull request merged**
