### PR TITLE
Add Stylistic Alternate Glyphs: a, t, y to Inter Text

### LINKED ISSUE #152: Feature Request: Add more stylistic alternates
I have a few stylistic alternates I'd like to see:

- Alternate lowercase 't' without the curve
- Alternate '@' symbol, which has an uppercase 'A' minus the crossbar in it.
- Alternate lowercase 'y' without the curve
- Alternate punctuation with squares instead of circles
-  Alternate lowercase 'j' without the tail
- Alternate uppercase 'Q' and 'R' with undulating tails
- Alternate lowercase and uppercase 'o & O' that look a bit more like a circle than an oval

A few of these ideas came from my own pet peeves about other fonts (I'm looking at you, Arial)

### PR DESCRIPTION
**Pull request by Derpitron**
### Lowercase a with horizontal terminal. 
Left: My alternate, Right: Original glyph
image

### Lowercase t with straight tail.
Left: My alternate, Right: Original glyph
image

### Lowercase y with straight tail
Left: My alternate, Right Original glyph
image

These stylistic alternates have corresponding character variant feature files, and I have created a new stylistic set ss05, for "straight tailed characters", including l.ss02, t.ss05, and y.ss05. 

I have designed these glyphs in Fontlab 7 for Windows, and exported to .glyphs format using the program's inbuilt exporter. However, I have noticed that attempting to build from this glyphs file using the Inter toolchain fails, as Fontlab's exporter seems to mis-generate certain sections of the files, e.g missing delimiters. It is too tedious of a process for me to find these malformed sections and manually correct them, and it is not possible for me to use the Glyphs app, as neither do I have access to a Mac, nor do I have a Glyphs license. 

I am able to generate .ufo files through FontLab 7, but I have not committed them to my fork as it may disrupt your repository structure.

This PR essentially closes #152, a feature request I made years ago.  

This is my first pull request to this repository, and my first time modifying the Inter font.

### CODE REVIEW

**Comment by Derpitron** [comment]
I managed to fix my .glyphs file using a text editor! This should rectify any formatting errors, though it is tedious to do it by hand. Now that I know that the issue is caused by my font designing software, and not my fault, it will still be tedious to re-edit the .glyphs file manually, but now I know the specific issues to look out for.

**Comment by Derpitron** [comment]
i am genuinely curious, why no new commits have been made to Inter since June!

**Comment by Derpitron** [comment]
Oh, that's understandable.

**Comment by TaigaYamada** [comment]
Thank you very much for this contribution!

I've been wanting a horizontal terminal version of lowercase "a" for some time now, but didn't have the tools/experience to cut a letter myself.

@Derpitron could you consider a vertical terminal version of lowercase "t" and "y" as well? (Currently inter has angled terminal for these)

**Comment by Derpitron** [comment]
hey Taiga, thanks for the kind words! I feel as though a straight terminal "t" and "y" would be too hard to distinguish from the original designs, be it at small sizes or large sizes. But I feel that my straight terminal "a" design would be more distinguishable at larger sizes, e.g for large body copy. 

I considered making a straight terminal variant when I just started designing, but then I would have to make alternate glyphs for not just "t" and "y", but for a lot of other glyphs across not just Latin but also Greek and Cyrillic character sets.

**Comment by rsms** [comment]
Hello and thank you for the offering. Really nice work. However there's a personality to any font and I fear adding these alternates would make Inter less "Inter" and more of a "a little bit of everything."

I have two suggestions:

1. If you are interested specifically in contributing to Inter, the Display font has a lot of glyph work to be done. Like, hundreds of glyphs. Working on that would be impactful (let me know if you want to do this and I can come up with a list of glyghs already done in Display.) I've updated [CONTRIBUTING.md](https://github.com/rsms/inter/blob/master/CONTRIBUTING.md#improvements-to-the-display-subfamily) with information.
2. If you dream of Inter looking & feeling differently, create your own fork of Inter where you can change the style completely freely to make it your own

Thank you for understanding!

**Comment by Derpitron** [comment]
It was fun working on this font, and even if it isn't merged with the original, it was a fun hobby for me to work on. I loved the community's approval of my work. I will continue to work on my own fork of this font alongside yours, and any bug fixes I will contribute upstream.  Thank you!

**Comment by rsms** [comment]
Lovely! Looking forward to seeing a what you create!

**Pull request closed without merging**
