### PR TITLE
docs: update license and README

### PR DESCRIPTION
**Pull request by auxiliarypower**
- Update the license file to reflect the current year and follow the format of the [Open Font License](https://scripts.sil.org/OFL_web).
- Correct some typos and missing commas in the README.md file.

### CODE REVIEW

**Comment by rsms** [comment]
Please open an issue describing the issues this patch solves. We can discuss there before we consider merging this. Thank you

**Comment by auxiliarypower** [comment]
- This commit resolves several issues in the .github/workflows/build-fonts.yml, README.md, docs/res/base.css, docs/_layouts/default.html and docs/res/grid.css files.

- In .github/workflows/build-fonts.yml, the runs-on value is changed from ubuntu-22.04 to ubuntu-latest to ensure compatibility with the latest version of Ubuntu and ubuntu-22.04 already has the zip utility installed by default, as stated in the [file](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#installed-apt-packages).
- In README.md, a redundant period is removed from the end of the hyperlink text for the LICENSE.txt file. This improves the readability and consistency of the document.
- In docs/res/base.css, several changes are made to improve the cross-browser compatibility and performance of the CSS code. These include:
- 1. Adding text-size-adjust property after -ms-text-size-adjust and -webkit-text-size-adjust properties to support Chrome 54+, Edge 79+ and Firefox browsers.
- 2. Reordering font-kerning, font-variant-ligatures, appearance, font-feature-settings and user-select properties after their vendor-prefixed versions to follow the [best practices] for writing CSS code.
- In docs/_layouts/default.html, a duplicate charset meta element is removed as it is unnecessary and may cause conflicts with the HTML validator.
- In docs/res/grid.css, the appearance property is reordered after the -webkit-appearance property for the same reason as above.

**Comment by auxiliarypower** [comment]
- Add commas after Inter trademark in README.md and default.html
- Add missing appearance property for cross-browser support in lab.css and ctxedit.css
- Fix spelling of animation property in ctxedit.css
- Fix typo of important keyword in base.css
- Add column-width property for multi-column layout in index.css

**Comment by rsms** [comment]
Again, please open an issue describing the issues this patch solves. We can discuss there before we consider merging this. 

Generally I don’t accept PRs to the readme and definitely not to the license text.

Additionally, you’ll want to break up this “a little bit of everything” PR into a few individual PRs, each that solves a specific problem.

For things like spelling mistakes please file an issue, do not make a PR.

Thank you for understanding

**Pull request closed without merging**
